### PR TITLE
added the index.html and js files

### PR DESCRIPTION
**Pull request by rymaspic**
Added the UI related files for testing.
(1) Added the index.html
(2) Added the js files
(3) Added the css files

Some UI elements for testing like Action are not included, when you write your own BDD code, you might need to add your own UI functions.
image

### CODE REVIEW

**Comment by kunal15** [comment]
Is it possible to improve the data representation? Like having products and rating on the same line as other fields instead of the 2nd line?

**Comment by Luolingwei** [comment]
> Is it possible to improve the data representation? Like having products and rating on the same line as other fields instead of the 2nd line?

Yes, we can improve the layout, now the column ```Products``` and ```Rating``` are not presented very well.

**Comment by Luolingwei** [comment]
One more thing, can we add a "None" tab to ```is_active```? Now it seems that we can not set this attribute to ```None``` when doing query.

**Comment by Luolingwei** [comment]
It seems that update API is not working correctly

**Pull request merged**
